---
Default Meta Description: manticore description
Default Meta Tags: manticore, default, tags
Telephone Grimsby: 01469552880
Telephone Hull: 01482 826635
Telephone Scunthorpe: 03303 331501
Name: Humberside Engineering Training Association Ltd.
Address: Copenhagen Road, Hull, East Riding of Yorkshire, HU7 0XJ
Reg No: '1007353'
VAT No: '347475233'
Charity No: '508775'
Twitter: http://www.twitter.com/HETA1967
Email: paul@eskimosoup.co.uk
Facebook: http://www.facebook.com/pages/HETA/188306187875314?ref=ts&sk=wall
